### ISSUE TITLE
Theme 

### ISSUE THREAD

**Issue by srlopez** [aragonopendata/presupuesto#10]
Hola David, en tu documentación hablas de un directorio 'theme-dvmi' como buen ejemplo de tema.
No soy capaz de encontrar dicho directorio.

Por otro lado, los logos de Aragon y AragonOpenData se encuentran en bugged_app/static/assets y no en el diretorio de theme_aragon. ¿eso es correcto?
Gracias

**Comment by dcabo** [comment]
Hola. Perdona el retraso. El tema de DVMI, y alguno más de proyectos similares (Rubí, Torrelodones, Móstoles), está en la [cuenta de github de Civio][1]. No recuerdo en qué parte de la documentación lo mencionaba, si me dices lo aclaro allí también.

Sobre lo del logo de Aragón voy a crear un issue para moverlos cuando tenga un momento.

[1]: https://github.com/civio

**Comment by srlopez** [comment]
Gracias David
DVMI está en el último párrafo del INSTALLL.md



 *Atentamente.*



    *Santiago R. López*
   srlopezh@gmail·com
   +34 675.703.184

**Comment by dcabo** [comment]
estupendo, acabo de arreglarlo, gracias!
