### ISSUE TITLE
Error en algunas URLs

### ISSUE THREAD

**Issue by grisendo** [aragonopendata/presupuesto#4]
Buenas tardes,

He conseguido instalar la aplicación en local, pero hay algunas secciones a las que no puedo acceder, así que recuerde, a las de municipios.

¿Esto puede ser debido a que no hay datos de municipios en la carpeta /data del repositorio?

El error exacto es (tanto en el listado de municipios como dentro de un municipio):

IndexError at /municipios
list index out of range
Request Method:	GET
Request URL:	http://localhost:8000/municipios
Django Version:	1.5
Exception Type:	IndexError
Exception Value:	
list index out of range
Exception Location:	/home/grisendo/sandbox/presupuesto/aragon/views/helpers.py in populate_years, line 49
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/grisendo/sandbox/presupuesto',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
Server time:	Sat, 17 Jan 2015 21:06:50 +0100

**Comment by dcabo** [comment]
Hola,

En efecto, si no cargas datos de municipios esa parte no te va a funcionar. Y no basta con que estén en el directorio `/data`, hay que cargarlos en la base de datos.

Los datos de municipio no están en el repo porque ocupaban mucho, pero los puedes descargar de la web de Open Data Aragón. Creo que [aquí](http://opendata.aragon.es/catalogo/presupuesto-y-ejecucion-presupuestaria-de-municipios-de-aragon) están todos.

**Comment by grisendo** [comment]
Muchas gracias,

¿Hay algún comando tipo python manage.py load_*** para volcarlos a base de datos?

**Comment by dcabo** [comment]
Sí, en el README hay un ejemplo:

    $ python manage.py load_budget_data comarca 2014Q1

y puedes mirar la "Documentación Técnica" en `/docs`.
